name: "Outside Collab Audit"

on:
  workflow_dispatch:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run audit
        run: |
          echo "Running audit"
          
          REPO="${{ github.repository }}"
          IFS='/' read -ra ADDR <<< "$REPO"
          OWNER="${ADDR[0]}"
          NAME="${ADDR[1]}"

          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d "{
            \"query\": \"query { repository(owner:\\\"$OWNER\\\" name:\\\"$NAME\\\") { collaborators(affiliation:OUTSIDE first:100) { nodes { login } } } }\"
          }" https://api.github.com/graphql)

          LOGINS=$(echo $RESPONSE | jq -r '.data.repository.collaborators.nodes[].login')
          echo $LOGINS

          # Convert logins to bulleted list
          BULLETED_LOGINS=$(echo "$LOGINS" | awk '{print "- "$0}')
          
          # Create issue
          echo "$BULLETED_LOGINS" | gh issue create --assignee polivebranch --assignee jennarutledge --title "Outside Collaborator Audit" --body-file -
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
